[build]
  publish = "."

# Redirige /merci vers merci.html (fix formulaire de contact)
[[redirects]]
  from = "/merci"
  to = "/merci.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
